=== cesar-cardinale/M1S2_DPR_Projet/Recettes.dtd
<!ENTITY Ingredients SYSTEM "Ingredients.xml">
<!ENTITY Auteurs SYSTEM "Auteurs.dtd">
<!ENTITY Categories SYSTEM "Categories.dtd">


<!ELEMENT Recettes (Recette*)>%Categories;
<!ELEMENT Recette (Titre,Resume,Photo,DatePublication,ListeIngredients,NbPersonnes,TempsPreparation,TempsCuisson,TempsRepos,Description,Note,ListeAuteurs)>
<!ELEMENT Titre (#PCDATA)>
<!ELEMENT Resume (#PCDATA)>
<!ELEMENT Photo (#PCDATA)>
<!ELEMENT DatePublication (#PCDATA)>
<!ELEMENT ListeIngredients (Ingredient*)>
<!ELEMENT Ingredient (#PCDATA)>
<!ELEMENT NbPersonnes (#PCDATA)>
<!ELEMENT TempsPreparation (#PCDATA)>
<!ELEMENT TempsCuisson (#PCDATA)>
<!ELEMENT TempsRepos (#PCDATA)>
<!ELEMENT Description (Etape*)>
<!ELEMENT Etape (#PCDATA)>
<!ELEMENT Note (#PCDATA)>
<!ELEMENT ListeAuteurs (Aute)>


<!ATTLIST Recette nom CDATA #REQUIRED difficulte (Très-facile|Facile|Normal|Difficile|Très-difficile) #REQUIRED>
<!ATTLIST Recette categorie IDREF #IMPLIED>
<!ATTLIST Ingredient nom CDATA #REQUIRED quantite CDATA #REQUIRED>
<!ATTLIST TempsPreparation unite (secondes|minutes|heures) #REQUIRED>
<!ATTLIST TempsCuisson unite (secondes|minutes|heures) #REQUIRED>
<!ATTLIST TempsRepos unite (secondes|minutes|heures) #REQUIRED>
<!ATTLIST Etape id CDATA #REQUIRED>

=== cesar-cardinale/M1S2_DPR_Projet/Recettes.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Recettes SYSTEM "Recettes.dtd"[
        <!ENTITY cat SYSTEM "Categories.xml">
        ]>


<Recettes>
    <Recette nom="Boeuf Wellington" difficulte="Très-facile" categorie="C2">
        <Titre>Bœuf Wellington</Titre>
        <Resume>Avez-vous déjà dégusté un bœuf wellington ? Sa cuisson en pâte feuilletée préserve sa saveur pour un résultat délicieux. Une belle spécialité anglaise.</Resume>
        <Photo>https://odelices.ouest-france.fr/images/recettes/boeuf_wellington.jpg</Photo>
        <DatePublication>12/09/2020</DatePublication>
        <ListeIngredients>
            <Ingredient nom="Filet de boeuf" quantite="1kg" />
            <Ingredient nom="Pâte feuilletée" quantite="1" />
            <Ingredient nom="Oignon" quantite="1" />
            <Ingredient nom="Champignons de paris" quantite="400g" />
            <Ingredient nom="Thym frais" quantite="1" />
            <Ingredient nom="Vin rouge" quantite="10cl" />
            <Ingredient nom="Huile d'olive" quantite="1" />
            <Ingredient nom="Jaune d'œuf" quantite="1" />
            <Ingredient nom="Sel" quantite="1" />
        </ListeIngredients>
        <NbPersonnes>8</NbPersonnes>
        <TempsPreparation unite="minutes">20</TempsPreparation>
        <TempsCuisson unite="minutes">50</TempsCuisson>
        <TempsRepos unite="minutes">0</TempsRepos>
        <Description>
            <Etape id="1">Faites chauffer l’huile dans une poêle. Salez le filet de bœuf et faites-le revenir sur toutes ses faces. Réservez.</Etape>
            <Etape id="2">Pelez et ciselez finement l’oignon. Lavez les champignons et coupez-les en petits dés.</Etape>
            <Etape id="3">Faites revenir les légumes 10 min dans une poêle avec un filet d’huile d’olive. Ajoutez le thym et le vin rouge. Laissez cuire 10 min pour faire réduire le jus. Salez.</Etape>
            <Etape id="4">Étalez la pâte feuilletée en un rectangle. Répartissez les champignons en laissant un bord sans garniture. Déposez le filet de bœuf et refermez la pâte feuilletée pour bien enfermer la viande.</Etape>
            <Etape id="5">Retournez le rôti et posez-le dans un plat allant au four.</Etape>
            <Etape id="6">Dorez la pâte avec un jaune d’œuf dilué avec une cuillerée à café d’eau. Faites 3 petites cheminées dans la pâte pour laisser la vapeur sortir pendant la cuisson.</Etape>
            <Etape id="7">Faites cuire 10 min dans le four préchauffé à 240°C puis baissez le four à 180°C et prolongez la cuisson 20 min.</Etape>
        </Description>
        <Note>4</Note>
        <ListeAuteurs>
            <Auteur nom="Tombini" />
        </ListeAuteurs>
    </Recette>
    &cat;
</Recettes>

=== cesar-cardinale/M1S2_DPR_Projet/Recettes_model.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Recettes SYSTEM "Recettes.dtd">
<Recettes>
	<Recette id-recette="R1"  difficulte="Très-facile" categorie="C2">
		<Titre>Bœuf Wellington</Titre>
		<Resume>Avez-vous déjà dégusté un bœuf wellington ? Sa cuisson en pâte feuilletée préserve sa saveur pour un résultat délicieux. Une belle spécialité anglaise.</Resume>
		<Photo>https://odelices.ouest-france.fr/images/recettes/boeuf_wellington.jpg</Photo>
		<DatePublication>12/09/2020</DatePublication>
		<ListeIngredients>
			<Ingredient id="I1" quantite="1kg"/>
			<Ingredient id="I2" quantite="1"/>
			<Ingredient id="I3" quantite="1"/>
			<Ingredient id="I4" quantite="400g"/>
			<Ingredient id="I5" quantite="1"/>
			<Ingredient id="I6" quantite="10cl"/>
			<Ingredient id="I7" quantite="1"/>
			<Ingredient id="I8" quantite="1"/>
			<Ingredient id="I9" quantite="1"/>
		</ListeIngredients>
		<NbPersonnes>8</NbPersonnes>
		<TempsPreparation unite="minutes">20</TempsPreparation>
		<TempsCuisson unite="minutes">50</TempsCuisson>
		<TempsRepos unite="minutes">0</TempsRepos>
		<Description>
			<Etape num="1">Faites chauffer l’huile dans une poêle. Salez le filet de bœuf et faites-le revenir sur toutes ses faces. Réservez.</Etape>
			<Etape num="2">Pelez et ciselez finement l’oignon. Lavez les champignons et coupez-les en petits dés.</Etape>
			<Etape num="3">Faites revenir les légumes 10 min dans une poêle avec un filet d’huile d’olive. Ajoutez le thym et le vin rouge. Laissez cuire 10 min pour faire réduire le jus. Salez.</Etape>
			<Etape num="4">Étalez la pâte feuilletée en un rectangle. Répartissez les champignons en laissant un bord sans garniture. Déposez le filet de bœuf et refermez la pâte feuilletée pour bien enfermer la viande.</Etape>
			<Etape num="5">Retournez le rôti et posez-le dans un plat allant au four.</Etape>
			<Etape num="6">Dorez la pâte avec un jaune d’œuf dilué avec une cuillerée à café d’eau. Faites 3 petites cheminées dans la pâte pour laisser la vapeur sortir pendant la cuisson.</Etape>
			<Etape num="7">Faites cuire 10 min dans le four préchauffé à 240°C puis baissez le four à 180°C et prolongez la cuisson 20 min.</Etape>
		</Description>
		<Note>4</Note>
		<ListeAuteurs>
			<Auteur idref="A1"/>
		</ListeAuteurs>
	</Recette>
    &cat;
    &aut;
    &ingr;
    &prod;
</Recettes>
